/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.paypay.analytics;

import com.paypay.analytics.collections.ImmutableQueue;

public class App {
  public static void main(String[] args) {
    final var queue = ImmutableQueue.<String>empty();
    var q1 = queue.enQueue("HELLO");
    System.out.println("q1 = " + q1);
    var q2 = q1.enQueue("WORLD");
    System.out.println("q2 = " + q2);
    final var q3 = q2.deQueue();
    System.out.println("q3 = " + q3);
  }
}
